apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image:  BouttesINSEE/DemoQueenMongo:latest
          imagePullPolicy: Always
          env :
            - name : SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demoqueen-mongodb
                  key: demoqueen-password
            - name : SPRING_DATASOURCE_USERNAME
              value :
            - name : SPRING_DATASOURCE_URL
              value : oui-mongodb.dev-hbouttes.svc.cluster.local